### ISSUE TITLE
Docker Hub Abandoned?

### ISSUE THREAD

**Issue by bcdady** [sonatype-nexus-community/iq-success-metrics#32]
* **What are you trying to do?**
Run Success Metrics container image as I did a few months ago.

* **What feature or behavior is this required for?**
Success Metrics reporting

* **How could we solve this issue? (Not knowing is okay!)**
Remove https://hub.docker.com/r/sonatypecommunity/iq-success-metrics, or otherwise update this page so that it's clear that the image available from Docker Hub is no longer functional nor supported.

* **Anything else?**

I encountered no errors when trying to run the latest container (`docker run --name iq-success-metrics --rm -it -v /tmp/output:/usr/src/app/output sonatypecommunity/iq-success-metrics:v5.7 success_metrics.py`), until this error output from the python script:

```python
Traceback (most recent call last):
  File "/usr/src/app/success_metrics.py", line 815, in <module>
    main()
  File "/usr/src/app/success_metrics.py", line 516, in main
    snap,appNumber,today = appChecker(args["url"])
  File "/usr/src/app/success_metrics.py", line 65, in appChecker
    rawData = response.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

cc @DarthHater @bhamail

**Comment by cmorenoserrano** [comment]
Hi Bryan,

That error message is for no data/empty data sent back by the API. Have a look around to see why you are getting no data sent back. I don't see a URL, user and password in your command (you might have removed them for security reasons).

We did leave a message about having deprecated this repository and pointing you to the new one. Funnily enough, we are just about to deprecate the "new" repository towards an even better one.

<img width="948" alt="Screenshot 2022-02-22 at 09 07 39" src="https://user-images.githubusercontent.com/50919218/155099344-6b3d1419-0afd-42c4-9a8c-eac97f35a929.png">

If you start using the java version, you will see that from version 85 we do support a docker version too. Let us know if you need help.
